### ISSUE TITLE
What does is do better than the loop option on youtube videos?

### ISSUE THREAD

**Issue by Nikit-Singh** [LaksCastro/yt-loop#1]
There is already a Loop option on YT videos when we right-click on them. What's different here?

**Comment by LaksCastro** [comment]
In fact nothing, this repository was not meant to be anything special besides allowing the looping of a youtube video. I didn't know about this YouTube loop option, thanks for sharing! =D

**Comment by Nikit-Singh** [comment]
Oh lol, no problemo xD.
Btw loved your lo-fi player, installed the PWA too.
Thinking of making one myself as a side project :D

**Comment by LaksCastro** [comment]
Oh, I'm glad you liked it! I read your message while listening to the Lofi-Player xD

I intend to implement some performance improvements and a random button.

I think it's a great idea to create one as a personal project, I'll follow you to find out when your project goes live! =D

Thanks,
Laks
